[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[main]]
  name = "About"
  weight = 10
  identifier = "about"
  url = "/about"

[[main]]
  name = "Services"
  weight = 20
  identifier = "services"
  url = "/services"

[[main]]
  name = "Work With Us"
  url = "/consult"
  weight = 30
  identifier = "work-with-us"

[[social]]
  name = "Linkedin"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-linkedin\"><path d=\"M12 9.55C12.917 8.613 14.111 8 15.5 8a5.5 5.5 0 0 1 5.5 5.5V21h-2v-7.5a3.5 3.5 0 0 0-7 0V21h-2V8.5h2v1.05zM5 6.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm-1 2h2V21H4V8.5z\"></path></svg>"
  url = "https://linkedin.com/in/devus"
  weight = 20